plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace 'com.core.engine'
    compileSdk 36

    defaultConfig {
        minSdk 26
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    buildFeatures {
        viewBinding false
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.androidx.documentfile
    implementation libs.kotlin.stdlib
}
